-- generated by sqlalchemy

CREATE TABLE IF NOT EXISTS happyvideo.`order` (	id BIGINT NOT NULL AUTO_INCREMENT, 
	customer_id BIGINT, 
	created_time INTEGER NOT NULL, 
	modified_time INTEGER NOT NULL, 
	orderid VARCHAR(128) NOT NULL, 
	resourceid VARCHAR(128), 
	resourcetype SMALLINT NOT NULL, 
	resourceinfo VARCHAR(300), 
	lvl1_user VARCHAR(128) NOT NULL, 
	lvl2_user VARCHAR(128) NOT NULL, 
	lvl3_user VARCHAR(128) NOT NULL, 
	platform VARCHAR(128), 
	status INTEGER NOT NULL, 
	price INTEGER NOT NULL, 
	lastupdateinfo VARCHAR(512), 
	failreason VARCHAR(256), 
	failreasoncode SMALLINT, 
	clientinfo VARCHAR(512), 
	history VARCHAR(512), 
	finishtime INTEGER, 
	thirdpartyorderid VARCHAR(128), 
	waittopayinfo VARCHAR(256), 
	payinfo VARCHAR(256), 
	PRIMARY KEY (id)
)ENGINE=InnoDB CHARSET=utf8;

CREATE INDEX ix_order_modified_time ON happyvideo.`order` (modified_time);
CREATE INDEX ix_order_customer_id ON happyvideo.`order` (customer_id);
CREATE INDEX ix_order_orderid ON happyvideo.`order` (orderid);
